#include <stdlib.h>
#include <stdio.h>
#include <sys/un.h>
#include <sys/socket.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#include <unistd.h>  
#include <sys/ioctl.h>
#include <stdarg.h>
#include <time.h>
#include <pthread.h>
#include <stdint.h>
#include <fcntl.h>    
#include <sys/stat.h>
#include <signal.h> 
#include <syslog.h>